# Generated by Django 3.0.4 on 2020-03-31 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Unique name of the server.', unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Timestamp at which this record was created.')),
                ('modified_on', models.DateTimeField(blank=True, editable=False, help_text='TImestamp at which this record was last modified.', null=True)),
                ('user', models.ForeignKey(help_text='User that created this server.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(db_index=True, help_text='Search query text.', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Timestamp at which this record was created.')),
                ('chat_server', models.ForeignKey(help_text='Chat server where search was made.', on_delete=django.db.models.fields.NullBooleanField, to='core.ChatServer')),
                ('user', models.ForeignKey(help_text='User for which history is recorded.', on_delete=django.db.models.fields.NullBooleanField, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
