# Generated by Django 3.0.4 on 2020-03-31 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatserver',
            options={'verbose_name': 'Chat Server', 'verbose_name_plural': 'Chat Servers'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'verbose_name': 'Search History', 'verbose_name_plural': 'Search Histories'},
        ),
    ]
