# Generated by Django 3.0.4 on 2020-04-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200331_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ('-created_on',), 'verbose_name': 'Search History', 'verbose_name_plural': 'Search Histories'},
        ),
        migrations.AlterField(
            model_name='chatserver',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp at which this record was created.'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp at which this record was created.'),
        ),
    ]
